name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-goversion
      - run: make cross
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            This is release `${{ env.GITHUB_REF_NAME }}` of Tanka (`tk`). 
            ## Install instructions

            #### Binary:
            ```bash
            # download the binary (adapt os and arch as needed)
            $ curl -fSL -o "/usr/local/bin/tk" "https://github.com/AidnAS/tanka/releases/download/${{ env.GITHUB_REF_NAME }}/tk-linux-amd64"

            # make it executable
            $ chmod a+x "/usr/local/bin/tk"

            # have fun :)
            $ tk --help
            ```
          draft: true
          files: |
            dist/*
